// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZT5f8u0rs5u2dx6OxIZ2tcbiintbUa48',
    appId: '1:626809982000:web:92d3a453d31f31ed51b1f5',
    messagingSenderId: '626809982000',
    projectId: 'library-app-71aff',
    authDomain: 'library-app-71aff.firebaseapp.com',
    storageBucket: 'library-app-71aff.firebasestorage.app',
    measurementId: 'G-94S47VRHYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU3uVxkdgNPacGfu5g4gdIpzbLPIKsGN0',
    appId: '1:626809982000:android:81da9bfe19c21cb151b1f5',
    messagingSenderId: '626809982000',
    projectId: 'library-app-71aff',
    storageBucket: 'library-app-71aff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoqHQZCbhb3KqBC6TUbBC2zHqpG4y86fs',
    appId: '1:626809982000:ios:3ee74e235e4d0d9751b1f5',
    messagingSenderId: '626809982000',
    projectId: 'library-app-71aff',
    storageBucket: 'library-app-71aff.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoqHQZCbhb3KqBC6TUbBC2zHqpG4y86fs',
    appId: '1:626809982000:ios:3ee74e235e4d0d9751b1f5',
    messagingSenderId: '626809982000',
    projectId: 'library-app-71aff',
    storageBucket: 'library-app-71aff.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZT5f8u0rs5u2dx6OxIZ2tcbiintbUa48',
    appId: '1:626809982000:web:653342e34a5244ec51b1f5',
    messagingSenderId: '626809982000',
    projectId: 'library-app-71aff',
    authDomain: 'library-app-71aff.firebaseapp.com',
    storageBucket: 'library-app-71aff.firebasestorage.app',
    measurementId: 'G-P1RGJXMLE5',
  );
}
